### ISSUE TITLE
FormeTextField value automatically disappear when scroll down

### ISSUE THREAD

**Issue by user97116** [wwwqyhme/forme#3]
I tried using controller and initial value but not work, when it disapper it not even display in form data

**Comment by wwwqyhme** [comment]
can you show me your code?

**Comment by wwwqyhme** [comment]
if you are using ListView , this is expected behavior. some widgets out of viewport will be disposed when ListView is scrolling.

if you don't have a performance issue , you can use SingleChildScrollView instead

**Comment by user97116** [comment]
Yes, with ListView it happens and with SingleChildScrollView works good.
